name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    #container: python:3.13-bullseye

    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: alice_core
          POSTGRES_USER: alice_core
          POSTGRES_PASSWORD: alice_core

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          APP_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          APP_SETTING_LOCAL_SETTINGS_PATH: "./app/alice/settings/templates/settings.github.py"
